#!/bin/bash

dir="$(dirname "$BASH_SOURCE")"
if [ -n "$REQUESTFILE_SH" ]; then
  bash -ce ". '$dir/../lib/request-file/bin/request-file.sh'" "autil request" "$@"
else
  ( exec -a "autil request" "$dir/../lib/request-file/bin/request-file.bin" "$@" )
fi
unset dir
