#!/bin/bash

dir="$(dirname "$BASH_SOURCE")"
timestamp=`date +%s%N`
envfile="$dir/.request.${time}.env"
bash "$dir/../lib/request-file/bin/request-file.sh" "$@" --exports-file "$envfile"
autil env "$envfile"
rm "$envfile"
unset dir timestamp envfile
