#!/bin/bash

comp_cword="$1"
shift;
comp_words=( "$@" )
prev="${comp_words[comp_cword-1]}"
cur="${comp_words[comp_cword]}"
if [ "$prev" = "vault" ]; then
  compgen -W "genkey encrypt decrypt" "$cur"
elif [ "$prev" = "encrypt" ] || [ "$prev" = "decrypt"]; then
  compgen -f "$cur"
fi
